Config for preview envs and setup instructions
bloom-works/co-care-directory pull request #6
Opened 2022-06-09 21:33 UTC by jeffmaher

Add configurations and documentation for running the app in Heroku, including preview environments that launch whenever a PR is submitted or changed (Heroku lingo: review apps). In additional to the added files, also setup a test app in Heroku (which I'll delete after this PR is closed)

- [App running](https://co-care-dir-jm-20220609.herokuapp.com/)
- [Heroku dashboard](https://dashboard.heroku.com/apps/co-care-dir-jm-20220609)

Since part of this was telling Docker and Heroku how to run the debug version of the app, I included dev setup instructions too (both with and without Docker) in the README file.

Note: I turned on review apps already, but new PRs might have a logged error until this is merged. But, no rush -- shouldn't hold anything up.

2022-06-09 21:37 UTC, jeffmaher commented
Heroku is spinning up the preview env too, so that should be available and listed in the PR in addition to the one in the description.

2022-06-09 22:02 UTC, cathydeng requested changes
just lil things, thx for the documentation 💖

2022-06-09 23:02 UTC, jlhogan commented on README.md
> +1. Access the app at `http://localhost:3000`
markup turns `1.` into consecutive numbers for ordered list :)

2022-06-09 23:06 UTC, jlhogan approved these changes

2022-06-09 23:06 UTC, jlhogan commented on docker-compose.yml
> +      - ./app:/app
this was just a result of running `create-react-app` within the repo... we can talk about if it would be preferred to pull the app up into base directory. no strong opinion on my end

2022-06-10 09:44 UTC, jeffmaher commented on README.md
> +1. Access the app at `http://localhost:3000`
Ha! Whoops. Fixed the repeating text.

2022-06-10 09:45 UTC, jeffmaher commented on docker-compose.yml
> +      - ./app:/app
Ah cool! My React newbie-ness thought maybe it was standard. I just shifted everything up to the base directory, as it makes a few other things easier for the CI scripts and the Docker setup.

2022-06-10 09:52 UTC, jeffmaher commented
@bloom-works/co-bha-care-directory-devs : Thanks for the review feedback! Made updates, but can wait until the ZIP lookup (#5 ) is merged before re-review so that I can handle the merge conflicts from `/app` stuff moving into the base directory.

2022-06-10 15:47 UTC, jeffmaher commented
@bloom-works/co-bha-care-directory-devs : All ready for re-review! Changes merged in from ZIP code stuff.

2022-06-10 17:06 UTC, cathydeng approved these changes
🚀

2022-06-10 17:21 UTC, merged